-
   name: temperature
   topic: devices/{mac}/temperature
   retention: -1 #forever
   type: float2
-
   name: pressure
   topic: devices/{mac}/pressure
   retention: 2592000 #30*24*60*60
   type: float1
-
   name: humidity
   topic: devices/{mac}/humidity
   retention: 604800 #7*24*60*60
   type: float1
-
   name: light
   topic: devices/{mac}/lux
   retention: 2592000 #30*24*60*60
   type: int
-
   name: battery
   topic: devices/{mac}/bat_persentage
   type: int
-
   name: adc
   topic: devices/{mac}/adc
   type: int
-
   name: rssi
   topic: devices/{mac}/rssi
   retention: 604800
   type: int
-
   name: ip
   topic: devices/{mac}/ip


