-
   name: temperature
   topic: devices/{mac}/sensors
   retention: -1 #forever
   field: temperature
   type: float2
-
   name: pressure
   topic: devices/{mac}/sensors
   retention: 2592000 #30*24*60*60
   field: pressure
   type: float1
-
   name: humidity
   topic: devices/{mac}/sensors
   retention: 604800 #7*24*60*60
   field: humidity
   type: float1
-
   name: light
   topic: devices/{mac}/sensors
   retention: 2592000 #30*24*60*60
   field: ambient_light
   type: int
-
   name: battery
   topic: devices/{mac}/sensors
   field: battery
   type: int
-
   name: rssi
   topic: devices/{mac}/sensors
   field: rssi
   type: int
-
   name: ip
   topic: devices/{mac}/sensors
   field: ip